[project]
name = "switi-reproducibility"
version = "0.1.0"
description = "Scripts to reproduce experiments run for the SWITi paper."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "careamics",
    "pooch>=1.9.0",
    "tilartmetrics",
]

tool.uv.package = false

[tool.uv.sources]
careamics = { git = "https://github.com/CAREamics/careamics.git", rev = "mc/feat/switi-merge" }
tilartmetrics = { git = "https://github.com/juglab/TilArtMetrics.git" }